# Generated by Django 4.2.5 on 2023-11-25 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0007_medicine_alter_prescription_medicine_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescription',
            name='medicine_name',
            field=models.CharField(default='Unknown Medicine', max_length=255),
        ),
        migrations.DeleteModel(
            name='Medicine',
        ),
    ]
