# Generated by Django 4.2.5 on 2023-11-25 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0008_alter_prescription_medicine_name_delete_medicine'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prescription',
            name='medicine_name',
        ),
        migrations.AddField(
            model_name='prescription',
            name='medicine1',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='prescription',
            name='medicine2',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='prescription',
            name='medicine3',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='prescription',
            name='medicine4',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
