# Generated by Django 4.2.5 on 2023-11-25 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0010_rename_medicine1_prescription_medicine_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reassignment',
            name='reassignment_reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
