# Generated by Django 4.2.5 on 2023-11-25 09:32

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0011_reassignment_reassignment_reason'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consultationhistory',
            name='reassignment_reason',
        ),
        migrations.RemoveField(
            model_name='consultationhistory',
            name='token_number',
        ),
        migrations.AddField(
            model_name='consultationhistory',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AddField(
            model_name='consultationhistory',
            name='prescription',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hospital.prescription'),
        ),
    ]
