# Generated by Django 4.2.5 on 2023-11-25 22:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0015_consultation_consumption_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prescription',
            name='consumption_time',
        ),
        migrations.RemoveField(
            model_name='prescription',
            name='medicine_name',
        ),
    ]
