# Generated by Django 4.2.5 on 2023-11-25 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0016_remove_prescription_consumption_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='consumption_time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='prescription',
            name='medicine_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
