# Generated by Django 4.2.5 on 2023-11-25 22:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0017_prescription_consumption_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consultation',
            name='prescription',
        ),
    ]
