# Generated by Django 4.2.5 on 2023-11-26 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0018_remove_consultation_prescription'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='prescription',
        ),
        migrations.AddField(
            model_name='appointment',
            name='consulted',
            field=models.BooleanField(default=False),
        ),
    ]
