# Generated by Django 4.2.5 on 2023-11-26 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0019_remove_appointment_prescription_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reassignment',
            name='consultation_history',
        ),
        migrations.RemoveField(
            model_name='reassignment',
            name='new_doctor',
        ),
        migrations.DeleteModel(
            name='ConsultationHistory',
        ),
        migrations.DeleteModel(
            name='Reassignment',
        ),
    ]
