# Generated by Django 4.2.5 on 2023-11-26 10:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0020_remove_reassignment_consultation_history_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultation',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
    ]
