# Generated by Django 4.2.5 on 2023-11-26 12:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0022_reassignmentrequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reassignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField()),
                ('consultations', models.ManyToManyField(blank=True, to='hospital.consultation')),
                ('current_doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='current_doctor', to='hospital.doctor')),
                ('new_doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='new_doctor', to='hospital.doctor')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospital.patient')),
            ],
        ),
        migrations.DeleteModel(
            name='ReassignmentRequest',
        ),
    ]
