# Generated by Django 4.2.5 on 2023-11-28 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0026_pharmacy_email_pharmacy_name_pharmacy_phone_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pharmacy',
            name='phone_number',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
