# Generated by Django 4.2.5 on 2023-11-28 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0032_receptionistprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ReceptionistProfile',
        ),
    ]
